package com.Bancos;

import java.util.HashMap;
import java.util.Map;

public class Bancos{
	//Variável responsável por guardar os nomes dos Bancos, tendo seu código como identificação. Atua como um pequeno DataBase.
	private Map<String, String> bancosDataBase = new HashMap<>();
	
	public String getBanco(String id) {
		return bancosDataBase.get(id);
	}
	
	public void initialyzeBanco() {
		//Adicionando os bancos a variável, com seus respectivos códigos como ID
		bancosDataBase.put("654", "Banco A.J. Renner S.A.");
		bancosDataBase.put("246", "Banco ABC Brasil S.A.");
		bancosDataBase.put("075", "Banco ABN AMRO S.A.");
		bancosDataBase.put("121", "Banco Agibank S.A.");
		bancosDataBase.put("025", "Banco Alfa S.A.");
		bancosDataBase.put("641", "Banco Alvorada S.A.");
		bancosDataBase.put("065", "Banco Andbank (Brasil) S.A.");
		bancosDataBase.put("213", "Banco Arbi S.A.");
		bancosDataBase.put("096", "Banco B3 S.A.");
		bancosDataBase.put("024", "Banco BANDEPE S.A.");
		bancosDataBase.put("318", "Banco BMG S.A.");
		bancosDataBase.put("752", "Banco BNP Paribas Brasil S.A.");
		bancosDataBase.put("107", "Banco BOCOM BBM S.A.");
		bancosDataBase.put("063", "Banco Bradescard S.A.");
		bancosDataBase.put("036", "Banco Bradesci BBI S.A.");
		bancosDataBase.put("122", "Banco Bradesco BERJ S.A.");
		bancosDataBase.put("204", "Banco Bradesco Cartões S.A.");
		bancosDataBase.put("394", "Banco Bradesco Financiamentos S.A.");
		bancosDataBase.put("237", "Banco Bradesco S.A.");
		bancosDataBase.put("218", "Banco BS2 S.A.");
		bancosDataBase.put("208", "Banco BTG Pactual S.A.");
		bancosDataBase.put("473", "Banco Caixa Geral - Brasil S.A.");
		bancosDataBase.put("412", "Banco Capital S.A.");
		bancosDataBase.put("040", "Banco Cargill S.A.");
		bancosDataBase.put("266", "Banco Cédula S.A.");
		bancosDataBase.put("739", "Banco Cetelem S.A.");
		bancosDataBase.put("233", "Banco Cifra S.A.");
		bancosDataBase.put("745", "Banco Citybank S.A.");
		bancosDataBase.put("241", "Banco Clássico S.A.");
		bancosDataBase.put("756", "Banco Cooperativo do Brasil S.A. - BANCOOB");
		bancosDataBase.put("748", "Banco Cooperativo Sicredi S.A.");
		bancosDataBase.put("222", "Banco Credit Agricole Brasil S.A.");
		bancosDataBase.put("505", "Banco Credit Suisse (Brasil) S.A.");
		bancosDataBase.put("069", "Banco Crefisa S.A.");
		bancosDataBase.put("003", "Banco da Amazônia S.A.");
		bancosDataBase.put("083", "Banco da China Brasil S.A.");
		bancosDataBase.put("707", "Banco Daycoval S.A.");
		bancosDataBase.put("300", "Banco de La Nacion Argentina");
		bancosDataBase.put("495", "Banco de La Provincia de Buenos Aires");
		bancosDataBase.put("494", "Banco de La Republica Oriental del Uruguay");
		bancosDataBase.put("001", "Banco do Brasil S.A.");
		bancosDataBase.put("047", "Banco do Estado de Sergipe S.A.");
		bancosDataBase.put("037", "Banco do Estado do Pará S.A.");
		bancosDataBase.put("041", "Banco do Estado do Rio Grande do Sul S.A.");
		bancosDataBase.put("004", "Banco do Nordeste do Brasil S.A.");
		bancosDataBase.put("265", "Banco Fator S.A.");
		bancosDataBase.put("224", "Banco Fibra S.A.");
		bancosDataBase.put("626", "Banco Ficsa S.A.");
		bancosDataBase.put("094", "Banco Finaxis S.A.");
		bancosDataBase.put("612", "Banco Guanabara S.A.");
		bancosDataBase.put("012", "Banco Irbusa S.A.");
		bancosDataBase.put("604", "Banco Industrial do Brasil S.A.");
		bancosDataBase.put("653", "Banco Indusval S.A.");
		bancosDataBase.put("077", "Banco Inter S.A.");
		bancosDataBase.put("630", "Banco Intercap S.A.");
		bancosDataBase.put("249", "Banco Investcreb Unibanco S.A.");
		bancosDataBase.put("184", "Banco Itaú BBA S.A.");
		bancosDataBase.put("029", "Banco Itaú Consignado");
		bancosDataBase.put("479", "Banco ItauBank S.A.");
		bancosDataBase.put("376", "Banco J. P. Morgan S.A.");
		bancosDataBase.put("074", "Banco J. Safra S.A.");
		bancosDataBase.put("217", "Banco John Deere S.A.");
		bancosDataBase.put("076", "Banco KDB S.A.");
		bancosDataBase.put("757", "Banco KEB HANA do Brasil S.A.");
		bancosDataBase.put("600", "Banco Luso Brasileiro S.A.");
		bancosDataBase.put("243", "Banco Máxima S.A.");
		bancosDataBase.put("720", "Banco Maxinvest S.A.");
		bancosDataBase.put("389", "Banco Mercantil do Brasil S.A.");
		bancosDataBase.put("370", "Banco Mizuho do Brasil S.A.");
		bancosDataBase.put("746", "Banco Modal S.A.");
		bancosDataBase.put("066", "Banco Morgan Stanley S.A.");
		bancosDataBase.put("456", "Banco MUFG Brasil S.A.");
		bancosDataBase.put("007", "Banco Nacional de Desenvolvimento Econômico e Social - BNDES");
		bancosDataBase.put("169", "Banco Olé Bonsucesso Consignado S.A.");
		bancosDataBase.put("079", "Banco Original do Agronegócio S.A.");
		bancosDataBase.put("212", "Banco Original S.A.");
		bancosDataBase.put("712", "Banco Ourinvest S.A.");
		bancosDataBase.put("623", "Banco PAN S.A.");
		bancosDataBase.put("611", "Banco Paulista S.A.");
		bancosDataBase.put("643", "Banco Pine S.A.");
		bancosDataBase.put("658", "Banco Porto Real de Investimentos S.A.");
		bancosDataBase.put("747", "Banco Rabobank International Brasil S.A.");
		bancosDataBase.put("633", "Banco Rendimento S.A.");
		bancosDataBase.put("741", "Banco Ribeirão Preto S.A.");
		bancosDataBase.put("120", "Banco Rodobens S.A.");
		bancosDataBase.put("422", "Banco Safra S.A.");
		bancosDataBase.put("033", "Banco Santander (Brasil) S.A.");
		bancosDataBase.put("743", "Banco Semear S.A.");
		bancosDataBase.put("754", "Banco Sistema S.A.");
		bancosDataBase.put("366", "Banco Société Générale Brasil S.A.");
		bancosDataBase.put("637", "Banco Sofisa S.A.");
		bancosDataBase.put("464", "Banco Sumitomo Mitsui Brasileiro");
		bancosDataBase.put("082", "Banco Topázio S.A.");
		bancosDataBase.put("634", "Banco Triângulo S.A.");
		bancosDataBase.put("018", "Banco Tricury S.A.");
		bancosDataBase.put("655", "Banco Votorantim S.A.");
		bancosDataBase.put("610", "Banco VR S.A.");
		bancosDataBase.put("119", "Banco Western Union do Brasil S.A.");
		bancosDataBase.put("124", "Banco Woori Bank do Brasil S.A.");
		bancosDataBase.put("081", "Banco Seguro S.A.");
		bancosDataBase.put("021", "BANESTES S.A. Banco do Estado do Espirito Santo");
		bancosDataBase.put("755", "Bank of America Merrill Lynch Banco Múltiplo S.A.");
		bancosDataBase.put("250", "BCV - Banco de Crédito e Varejo S.A.");
		bancosDataBase.put("144", "BEXS Banco de Câmbio S.A.");
		bancosDataBase.put("017", "BNY Mellon Banco S.A.");
		bancosDataBase.put("126", "BR Partners Banco de Investimento S.A.");
		bancosDataBase.put("125", "Brasil Plural S.A. - Banco Múltiplo");
		bancosDataBase.put("070", "BRB - Banco de Brasília S.A.");
		bancosDataBase.put("092", "Brickell S.A. - Crédito, Financiamento e Investimento");
		bancosDataBase.put("104", "Caixa Econômica Federal");
		bancosDataBase.put("320", "China Construction Bank (Brasil) Banco Múltiplo S.A.");
		bancosDataBase.put("477", "Citybank N.A.");
		bancosDataBase.put("163", "Commerzbank Brasil S.A. - Banco Múltiplo");
		bancosDataBase.put("136", "CONFEDERACAO NACIONAL DAS COOPERATIVAS CENTRAIS UNICREDS Ltda.");
		bancosDataBase.put("097", "Cooperativa Central de Crédito Noroeste Brasileiro Ltda.");
		bancosDataBase.put("487", "Deutsche Bank S.A. - Banco Alemão");
		bancosDataBase.put("064", "Goldman Sachs do Brasil Banco Múltiplo S.A.");
		bancosDataBase.put("135", "Gradual Corretora de Câmbio, Títulos e Valores Mobiliários S.A.");
		bancosDataBase.put("078", "Haitong Banco de Investimento do Brasil S.A.");
		bancosDataBase.put("062", "Hipercard Banco Múltiplo S.A.");
		bancosDataBase.put("269", "HSBC Brasil S.A. - Banco de Investimento");
		bancosDataBase.put("132", "ICBC do Brasil Banco Múltiplo S.A.");
		bancosDataBase.put("492", "ING Bank N.V");
		bancosDataBase.put("139", "Intesa Sampaolo Brasil S.A. - Banco Múltiplo");
		bancosDataBase.put("652", "Itaú Unibanco Holding S.A.");
		bancosDataBase.put("341", "Itaú Unibanco S.A.");
		bancosDataBase.put("488", "JPMorgan Chase Bank, National Association");
		bancosDataBase.put("399", "Kirton Bank S.A. - Banco Múltiplo");
		bancosDataBase.put("128", "MS Bank S.A. Banco de Câmbio");
		bancosDataBase.put("014", "Natixis Brasil S.A. Banco Múltiplo");
		bancosDataBase.put("753", "Novo Banco Continental S.A. - Banco Múltiplo");
		bancosDataBase.put("613", "Omni Banco S.A.");
		bancosDataBase.put("254", "Paraná Banco S.A.");
		bancosDataBase.put("751", "Scotiabank Brasil S.A. Banco Múltiplo");
		bancosDataBase.put("118", "Standard Chartered Bank (Brasil) S/A-Bco Invest.");
		bancosDataBase.put("095", "Travelex Banco de Câmbio S.A.");
		bancosDataBase.put("129", "UBS Brasil Banco de Investimento S.A.");
		bancosDataBase.put("084", "Uniprime Norte do Paraná Coop de Economia e Crédito Mútuo dos Médicos, Profissionais das Ciências");
		bancosDataBase.put("091", "Unicred Central do Rio Grande do Sul");
		bancosDataBase.put("098", "CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL");
		bancosDataBase.put("089", "Cooperativa de Crédito Rural da Região da Mogiana");
		bancosDataBase.put("087", "Cooperativa Central de Economia e Crédito Mútuo das Unicreds de Santa Catarina e Paraná");
		bancosDataBase.put("090", "Cooperativa Central de Economia e Crédito Mútuo - SICOOB UNIMAIS");
		bancosDataBase.put("085", "Cooperativa Central de Crédito Urbano-CECRED");
		bancosDataBase.put("114", "Central das Cooperativas de Economia e Crédito Mútuo do Estado do Espírito Santo Ltda.");
	}
}
